development:
  adapter: postgresql
  database: multi_dev
  username: postgres
  password: password
  host: localhost
test: &TEST
  adapter: postgresql
  database: multi_test
  username: postgres
  password: password
  host: localhost

  production:
    adapter: postgresql
    database: multi_prod
    username:
    password:
    host: localhost